name: Call Reusable Create/Consume

on:
  workflow_dispatch:

jobs:
  call_reusable:
    uses: afnanmalik-eurus/Composite-Action/.github/workflows/reusable-create-consume.yml@main
    with:
      filename: hello.txt

  show_output:
    needs: [call_reusable]
    runs-on: ubuntu-latest
    steps:
      - name: Print returned file-path
        run: |
          echo "Reusable workflow returned file-path: ${{ needs.call_reusable.outputs.file_path }}"
