name: Developer Trigger Workflow

on:
  workflow_dispatch:   

jobs:
  trigger-devops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read hello.txt
        id: read_file
        run: |
          CONTENT=$(cat hello.txt)
          echo "file_content<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Call reusable workflow from DevOps repo
        uses: afnanmalik-eurus/TestCompositeAction/.github/workflows/reusable-workflow.yaml@main
        with:
          file_content: ${{ steps.read_file.outputs.file_content }}
