name: Developer Trigger Workflow

on:
  workflow_dispatch:

    
jobs:
  call-reusable:
    uses: afnanmalik-eurus/TestCompositeAction/.github/workflows/reusable-workflow.yaml@main
    with:
      file-path: hello.txt

