name: Developer Trigger Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable:
    runs-on: ubuntu-latest
    uses: afnanmalik-eurus/TestCompositeAction/.github/workflows/reusable-workflow.yaml@main
    with:
      file-path: hello.txt
