name: Calling Compiste Action

on:
    push:
        branches:
            - main

jobs:
    calling_composite_action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/
              with:
                node-version: '22.15'


