name: Calling Compiste Action

on:
    push:
        branches:
            - main
    workflow_dispatch:
      

jobs:
    calling_composite_action:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Run composite action
            id: composite
            uses: afnanmalik-eurus/TestCompositeAction/.github/actions/deploy@main
            with:
              node-version: '18.x'
            env:
              GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

          - name: Print summary
            run: |
              echo "Main action completed successfully"



