name: Calling Compiste Action

on:
    push:
        branches:
            - main
    workflow_dispatch:
      

jobs:
    calling_composite_action:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Run create-file action
            uses: ./.github/actions/create-file
            id: create_file

          - name: Run consume-file action with created path
            uses: ./.github/actions/consume-file
            with:
              file-path: ${{ steps.create_file.outputs.file-path }}

          - name: Print summary
            run: |
              echo "Created file path: ${{ steps.create_file.outputs.file-path }}"



