name: Calling Compiste Action

on:
    push:
        branches:
            - main
    workflow_dispatch:
      

jobs:
    calling_composite_action:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            id: my-action
          - uses: ./.github/actions/
            with:
              node-version: 22.15

          - name: Print Output
            run: echo "Repo Owner is ${{ steps.my-action.outputs.repoOwner }}
            


