name: Calling Compiste Action

on:

    workflow_dispatch:
      

jobs:
    calling_composite_action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/
              with:
                node-version: 22.15


