name: Call Composite Action

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call Cat Hello Action
        uses: afnanmalik-eurus/TestCompositeAction@main
