name: Publish to nexus
on:
  workflow_dispatch:
jobs:
  build:
    name: Build & Publish
    runs-on: [self-hosted, cybercube-dev-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        if: github.ref == 'refs/heads/master'  # Run release deploy only on master branch
        uses: CyberCubeAnalyticsInc/action-artifact-delivery/maven/deploy@dev
        with:
          nexus_user: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
      - name: Publish Snapshot
        if: github.ref != 'refs/heads/master'  # Run snapshot deploy on other branches
        uses: CyberCubeAnalyticsInc/action-artifact-delivery/maven/deploy@dev
        with:
          nexus_user: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
